# Generated by Django 3.2.7 on 2023-03-26 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_auto_20230326_1128'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='image',
            field=models.ImageField(blank=True, upload_to='article/%Y/%m/%d/'),
        ),
    ]
